### PR TITLE
Profile Update

### PR DESCRIPTION
**Pull request by RaiVaibhav**
Added STUDENT and Contributing.md

### CODE REVIEW

**Comment by rishabh-bansal** [comment]
Will be merging it in October, so you can get benefit from Hacktoberfest. :)

**Comment by RaiVaibhav** [comment]
@rishabh-bansal  sir yesterday i have made a approx 20 commit out of which 3-4 gtes merge , so this means it will not count on hacktoberfest??

**Comment by rishabh-bansal** [comment]
Don't call me Sir, you can call me Rishabh Bhaiya :)
Yes, they won't be counted in Hacktoberfest, I made the same mistake. Also, someone told me that if the PR is merged in October, then it maybe be counted in Hacktoberfest. Happy Coding.

**Comment by RaiVaibhav** [comment]
Thanks Bhaia

**Comment by RaiVaibhav** [comment]
Bhaia closing this request , i will reopen in october 1st , hope you will understand

**Pull request closed without merging**
