### PR TITLE
Added my profile(Fenil Gandhi) and my name to Contribting.md

### PR DESCRIPTION
**Pull request by fenilgandhi**

### CODE REVIEW

**Comment by jesuiscamille** [comment]
resolve conflicts plz

**Comment by fenilgandhi** [comment]
@jesuiscamille Could you be more specific

**Comment by jesuiscamille** [comment]
To resolve conflicts, for this specific pull request, I recommend you to re-clone the git, and re-add your name. Be sure to place it at the end of the file, and to not edit other lines.

Have a good day =).
poke @rishabh-bansal

**Comment by fenilgandhi** [comment]
Done. Hope there's no bug in this one. @jesuiscamille  
https://github.com/rishabh-bansal/Make-a-Pull-Request/pull/431

**Pull request closed without merging**
