### PR TITLE
About my Self

### PR DESCRIPTION
**Pull request by RaiVaibhav**

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
@Logan1x  why it is showing conflict i don't know

**Comment by RaiVaibhav** [comment]
@rishabh-bansal  can you help me??

**Comment by Logan1x** [comment]
might because the repo updated after you cloned and your local copy was not updated when you pushed. Although i did had any problem before.

**Comment by Logan1x** [comment]
You can try with cloning again

**Pull request closed without merging**
